---
- hosts: esxi-host
  gather_facts: false
  tasks:
  - name: Write new instance host key to known hosts
    shell: |
      'ssh-keyscan -H {{inventory_hostname}}' >> ~/.ssh/known_hosts
  - name: Power on newly created VM
    shell: |
      vim-cmd vmsvc/power.on $(vim-cmd vmsvc/getallvms | grep -i testWithJenkins | cut -d " " -f 1-4)
  - name: Wait for VM to get an IP address
    pause:
      seconds: 90
  - name: Creating inventory file
    shell: |
      echo -e \[docker]\\n$(vim-cmd vmsvc/get.summary $(vim-cmd vmsvc/getallvms | grep -i testWithJenkins | cut -d " " -f 1-4) | grep -i address | cut -d " " -f 9 | sed 's/"//g' | sed 's/,//g') > /tmp/dockerinventory